apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: student-259281
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
