apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: student-259281
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: tadzislaw33/frontend:latest
        env:
        - name: REACT_APP_BACKEND_URL
          value: http://backend:5000
        ports:
        - containerPort: 3000
